var subtitles = [
{'eng': 'I teach chemistry.', 'time': '00:12', 'chn': '我是一名化学老师。', 'start': 12},
{'eng': '(Explosion)', 'time': '00:15', 'chn': '（爆炸声）', 'start': 15},
{'eng': 'All right, all right. So more than just explosions, chemistry is everywhere. Have you ever found yourself at a restaurant spacing out just doing this over and over? Some people nodding yes. Recently, I showed this to my students, and I just asked them to try and explain why it happened. The questions and conversations that followed were fascinating. Check out this video that Maddie from my period three class sent me that evening.', 'time': '00:16', 'chn': '大家没吓着吧！ 除了爆炸， 化学在我们生活中随处可见。 你有没有试过在餐厅里空闲无聊时 一遍又一遍的玩这个东西呢？ 我看到有人点头了。 最近，我给我的学生们做了上面那个实验， 并要求学生们自己动手去体验并解析这一现象为何发生。 在实验中，学生们提出的问题和进行的对话 很有意思。 请看一下这个视频， 这是我第三节课上的学生Maddie，在当天晚上发给我的。', 'start': 16},
{'eng': '(Clang) (Laughs)', 'time': '00:57', 'chn': '（铛）（笑声）', 'start': 57},
{'eng': "Now obviously, as Maddie's chemistry teacher, I love that she went home and continued to geek out about this kind of ridiculous demonstration that we did in class. But what fascinated me more is that Maddie's curiosity took her to a new level. If you look inside that beaker, you might see a candle. Maddie's using temperature to extend this phenomenon to a new scenario.", 'time': '00:59', 'chn': '当然了，作为Maddie的化学老师， 我非常欣慰她放学回家后还继续研究， 并演示了一个这么好玩的实验。 这个实验跟我们在课堂上做的差不多。 但最吸引我的是， Maddie的好奇心将她的化学学习提升到了一个新的高度。 如果你认真看一下那个烧杯， 你会看到一根蜡烛。 Maddie在实验中使用了温度， 对课堂上学到的实验赋予了新意。', 'start': 59},
{'eng': "You know, questions and curiosity like Maddie's are magnets that draw us towards our teachers, and they transcend all technology or buzzwords in education. But if we place these technologies before student inquiry, we can be robbing ourselves of our greatest tool as teachers: our students' questions. For example, flipping a boring lecture from the classroom to the screen of a mobile device might save instructional time, but if it is the focus of our students' experience, it's the same dehumanizing chatter just wrapped up in fancy clothing. But if instead we have the guts to confuse our students, perplex them, and evoke real questions, through those questions, we as teachers have information that we can use to tailor robust and informed methods of blended instruction.", 'time': '01:24', 'chn': '要知道，像Maddie这样带着疑问并怀有一颗好奇心， 是让学生更亲近老师的一种魔力 他们超脱了所有教学技术 和高大空的流行语。 如果我们在学生提问之前，就把这些技术呈现出来 我们将毁掉我们作为老师 手中最强大的武器——学生们的疑问。 比如说，在教室里借助移动电子设备 将一堂沉闷的课快速讲完 或许会节省些老师进行指导的时间， 但是，如果这是学生在课堂上所能收获的体验， 那这种照本宣科的无趣 只是华而不实的教学罢了。 但是，如果我们有胆量 去引起学生们的疑问，让他们感到困惑， 唤起他们提出真正的问题， 然后从他们的问题里，老师可以得到很多信息 来帮助作些调整教学 采用多样化的教学方法', 'start': 84},
{'eng': "So, 21st-century lingo jargon mumbo jumbo aside, the truth is, I've been teaching for 13 years now, and it took a life-threatening situation to snap me out of 10 years of pseudo-teaching and help me realize that student questions are the seeds of real learning, not some scripted curriculum that gave them tidbits of random information.", 'time': '02:20', 'chn': '这样，21世纪的那些术语行话就不会像魔咒一样难懂了。 事实是，今年是我从教的第13个年头， 我曾碰到过一件生死悠关的事 才将我从10年的伪教学中拉了出来 我这才明白，学生带着疑问来学习的心态 才能使他们学习到真正有意义的东西 而不是照本宣科的课程， 课程本身只能给学生提供一些随机的信息而已。', 'start': 140},
{'eng': 'In May of 2010, at 35 years old, with a two-year-old at home and my second child on the way, I was diagnosed with a large aneurysm at the base of my thoracic aorta. This led to open-heart surgery. This is the actual real email from my doctor right there. Now, when I got this, I was -- press Caps Lock -- absolutely freaked out, okay? But I found surprising moments of comfort in the confidence that my surgeon embodied. Where did this guy get this confidence, the audacity of it?', 'time': '02:47', 'chn': '2010年5月份，当时我35岁， 我已经有个2岁大的孩子，我的第二个孩子也即将出生， 当时我被诊断为患有大动脉瘤 这个肿瘤长在我的胸主动脉上。 因此，我要需做一个开腔手术。 这就是当时我的医生写给我的电子邮件。 当我收到他的邮件时，我的头都大了 当时真的完全被吓坏了！ 但我还是得到些许意外的安慰 这种安慰来源于我的外科医生的自信心。 他的自信心来是打哪儿来的呢？来自于他的大胆吗？', 'start': 167},
{'eng': "So when I asked him, he told me three things. He said first, his curiosity drove him to ask hard questions about the procedure, about what worked and what didn't work. Second, he embraced, and didn't fear, the messy process of trial and error, the inevitable process of trial and error. And third, through intense reflection, he gathered the information that he needed to design and revise the procedure, and then, with a steady hand, he saved my life.", 'time': '03:21', 'chn': '我问他这个问题，他跟我讲了三件事情。 他说，第一，他的好奇心驱使他去 就手术的程序预设了很多硬性问题， 把各种可行和不可行的方案全都想遍了。 第二，不要害怕逃避，要勇于面对 尝试与错误中的各种冗杂问题， 和不可避免的过程。 第三，通过紧张有致的综合思考， 他获取了他所需的信息 以此来设计和修改手术的进程， 最后，他胸有成竹地帮我做了手术，救了我一命。', 'start': 201},
{'eng': "Now I absorbed a lot from these words of wisdom, and before I went back into the classroom that fall, I wrote down three rules of my own that I bring to my lesson planning still today. Rule number one: Curiosity comes first. Questions can be windows to great instruction, but not the other way around. Rule number two: Embrace the mess. We're all teachers. We know learning is ugly. And just because the scientific method is allocated to page five of section 1.2 of chapter one of the one that we all skip, okay, trial and error can still be an informal part of what we do every single day at Sacred Heart Cathedral in room 206. And rule number three: Practice reflection. What we do is important. It deserves our care, but it also deserves our revision. Can we be the surgeons of our classrooms? As if what we are doing one day will save lives. Our students our worth it. And each case is different.", 'time': '03:52', 'chn': '我从他充满智慧的言语中学到很多， 那年秋季，在我回校上课前， 我也给自己的教学定了三条规则， 至今，我一直在我的教学中遵循这三条规则。 第一条规则：把学生的好奇心放在第一位。 学生的问题是帮助教师进行重要学习指导的窗口， 而不是反其道而行之。 第二条规则：勇于面对各种冗杂。 我们都是教师。我们知道学习绝非易事。 这是因为，科学的方法已经写在 课本第五页的第一章第一部分的第二节里了 而这章又刚好是我们跳过不讲的： 试错法（通过反复试验来消除误差）。 这种方法仍然是 我们每天在圣心大教堂206室里 所采用的一种非正规方法。 第三条：实践反思。 我们做的是重要的事。它值得我们关注， 而且也值得我们去进行修正。 我们这些老师能不能成为课堂中的外科医生呢？ 我们所教的东西或许在将来的某一天可能会救别人一命。 我们的学生，我们得珍惜。 而每个个体都是不同的。', 'start': 232},
{'eng': '(Explosion)', 'time': '04:58', 'chn': '（爆炸声）', 'start': 298},
{'eng': 'All right. Sorry. The chemistry teacher in me just needed to get that out of my system before we move on.', 'time': '04:59', 'chn': '对不起，太大声了。 作为化学老师，我得先做好这三点 然后才能教好学生。', 'start': 299},
{'eng': 'So these are my daughters. On the right we have little Emmalou -- Southern family. And, on the left, Riley. Now Riley\'s going to be a big girl in a couple weeks here. She\'s going to be four years old, and anyone who knows a four-year-old knows that they love to ask, "Why?" Yeah. Why. I could teach this kid anything because she is curious about everything. We all were at that age. But the challenge is really for Riley\'s future teachers, the ones she has yet to meet. How will they grow this curiosity?', 'time': '05:05', 'chn': '这是我的两个女儿的照片。 右边那个是Emmalou——南方家族的人。 左边那位是Riley。 再过几周，Riley就要成为一个大女孩了。 她的4岁生日快到了， 众所周知，一个4岁的孩子 总是喜欢问：“为什么？” 对。他们喜欢问这个问题。 我可以教给我女儿任何东西 因为她对什么都感兴趣。 我们所有人在4岁时都这样的。 但是Riley未来的老师 将要面临很大的挑战了， 他们会怎样来培养她的好奇心呢？', 'start': 305},
{'eng': "You see, I would argue that Riley is a metaphor for all kids, and I think dropping out of school comes in many different forms -- to the senior who's checked out before the year's even begun or that empty desk in the back of an urban middle school's classroom. But if we as educators leave behind this simple role as disseminators of content and embrace a new paradigm as cultivators of curiosity and inquiry, we just might bring a little bit more meaning to their school day, and spark their imagination.", 'time': '05:41', 'chn': '其实，我在用Rildy来喻指所有的孩子。 我知道，辍学会以各种形式出现—— 比如高中学生还没开学就辍学了， 或者市区中学教室里后排空着的课桌。 但是如果我们不仅仅是扮演 知识传播者的角色， 而且还开创一种新的教学模式 去激发学生的好奇心和探究兴趣， 我们将会为学生的求学带来更多意义 唤醒他们的想象力。', 'start': 341},
{'eng': 'Thank you very much.', 'time': '06:14', 'chn': '非常感谢你们。', 'start': 374},
{'eng': '(Applause)', 'time': '06:16', 'chn': '（掌声）', 'start': 376}
];

module.exports.subtitles = subtitles;