var subtitles = [
{'eng': 'I have spent my entire life either at the schoolhouse, on the way to the schoolhouse, or talking about what happens in the schoolhouse.', 'start': 13, 'time': '00:13', 'chn': '我这辈子 要么是在学校，要么在去学校的路上， 要么是在讨论学校里发生了什么事。'},
{'eng': '(Laughter)', 'start': 23, 'time': '00:23', 'chn': '（笑声）'},
{'eng': "Both my parents were educators, my maternal grandparents were educators, and for the past 40 years, I've done the same thing. And so, needless to say, over those years I've had a chance to look at education reform from a lot of perspectives. Some of those reforms have been good. Some of them have been not so good. And we know why kids drop out. We know why kids don't learn. It's either poverty, low attendance, negative peer influences... We know why. But one of the things that we never discuss or we rarely discuss is the value and importance of human connection. Relationships.", 'start': 24, 'time': '00:24', 'chn': '我的父母都是教育家， 我的外祖父母也都是搞教育的， 过去40年我也在从事同样的事业。 所以，很显然，过去的这些年里， 我有机会从各个角度 审视教育改革。 一些改革是有成效的。 而另一些却收效甚微。 我们知道孩子们为什么掉队辍学。 我们知道孩子们为什么学不下去。 原因无非是贫穷，低出席率， 同龄人的坏影响。 我们知道为什么。 但是我们从未讨论 或者极少讨论的是 人和人之间的那种联系的 价值和重要性。 这就是“关系”。'},
{'eng': "James Comer says that no significant learning can occur without a significant relationship. George Washington Carver says all learning is understanding relationships. Everyone in this room has been affected by a teacher or an adult. For years, I have watched people teach. I have looked at the best and I've looked at some of the worst.", 'start': 68, 'time': '01:08', 'chn': 'James Comer (美国著名 儿童精神科医师）说过， 没有强有力的联系， 学习就不会有显著的进步。 George Washington Carver （美国著名教育学家）说过， 学习就是理解各种关系。 在座的各位都曾经被一位老师 或者一个成年人影响过。 这么多年，我都在看人们怎么教学。 我看过最好的，也看过最差的。'},
{'eng': 'A colleague said to me one time, "They don\'t pay me to like the kids. They pay me to teach a lesson. The kids should learn it. I should teach it, they should learn it, Case closed."', 'start': 94, 'time': '01:34', 'chn': '一次有个同事跟我说， “我的职责不是喜欢那些孩子们。 我的职责是教书。 孩子们就该去学。 我管教课，他们管学习。 就是这么个理儿。”'},
{'eng': 'Well, I said to her, "You know, kids don\'t learn from people they don\'t like."', 'start': 105, 'time': '01:45', 'chn': '然后，我就跟她说， “你知道，孩子们可不跟他们讨厌的人学习。”'},
{'eng': '(Laughter)', 'start': 111, 'time': '01:51', 'chn': '（笑声）'},
{'eng': '(Applause)', 'start': 113, 'time': '01:53', 'chn': '（掌声）'},
{'eng': 'She said, "That\'s just a bunch of hooey."', 'start': 119, 'time': '01:59', 'chn': '她接着说，“一派胡言。”'},
{'eng': 'And I said to her, Well, your year is going to be long and arduous, dear.', 'start': 122, 'time': '02:02', 'chn': '然后我对她说， “那么亲爱的，你这一年会过得 十分漫长和痛苦。”'},
{'eng': "Needless to say, it was. Some people think that you can either have it in you to build a relationship, or you don't. I think Stephen Covey had the right idea. He said you ought to just throw in a few simple things, like seeking first to understand, as opposed to being understood. Simple things, like apologizing. You ever thought about that? Tell a kid you're sorry, they're in shock.", 'start': 128, 'time': '02:08', 'chn': '事实也果真如此。 有些人认为 一个人或者天生可以建立一种关系， 或者压根儿不具有这种能力。 我认为Stephen Covey （美国教育家）是对的。 他说你只需要做一些简单的事情， 比如试着首先理解他人， 而不是想要被理解， 比如道歉。 你想过吗？ 跟一个孩子说你很对不起， 他们都惊呆了。'},
{'eng': '(Laughter)', 'start': 151, 'time': '02:31', 'chn': '（笑声）'},
{'eng': "I taught a lesson once on ratios. I'm not real good with math, but I was working on it.", 'start': 153, 'time': '02:33', 'chn': '我有一次讲比例。 我数学不是很好，但是我当时在教数学。'},
{'eng': '(Laughter)', 'start': 158, 'time': '02:38', 'chn': '（笑声）'},
{'eng': "And I got back and looked at that teacher edition. I'd taught the whole lesson wrong.", 'start': 159, 'time': '02:39', 'chn': '我下课回到家，翻看了教师用书。 我完全教错了。'},
{'eng': '(Laughter)', 'start': 164, 'time': '02:44', 'chn': '（笑声）'},
{'eng': 'So I came back to class the next day and I said, "Look, guys, I need to apologize. I taught the whole lesson wrong. I\'m so sorry."', 'start': 165, 'time': '02:45', 'chn': '所以我第二天回到班上说， “同学们，我要道歉。 我昨天的课都教错了。我非常抱歉。”'},
{'eng': 'They said, "That\'s okay, Ms. Pierson. You were so excited, we just let you go."', 'start': 174, 'time': '02:54', 'chn': '他们说，“没关系，Pierson老师。 您当时教得非常投入，我们就让您继续了。”'},
{'eng': 'I have had classes that were so low, so academically deficient, that I cried. I wondered, "How am I going to take this group, in nine months, from where they are to where they need to be? And it was difficult, it was awfully hard. How do I raise the self-esteem of a child and his academic achievement at the same time?', 'start': 182, 'time': '03:02', 'chn': '我曾经教过程度非常低的班级， 学术素养差到我都哭了。 我当时就想，我怎么能在9个月之内 把这些孩子 提升到他们必须具备的水平？ 这真的很难，太艰难了。 我怎么能让一个孩子重拾自信的同时， 在学术上也有进步？'},
{'eng': 'One year I came up with a bright idea. I told all my students, "You were chosen to be in my class because I am the best teacher and you are the best students, they put us all together so we could show everybody else how to do it."', 'start': 207, 'time': '03:27', 'chn': '有一年我有了一个非常好的主意。 我告诉我的学生们， “你们进了我的班级， 因为我是最好的老师， 而你们是最好的学生， 他们把我们放在一起， 来给其他人做个好榜样。”'},
{'eng': 'One of the students said, "Really?"', 'start': 223, 'time': '03:43', 'chn': '一个学生说，“真的吗？”'},
{'eng': '(Laughter)', 'start': 225, 'time': '03:45', 'chn': '（笑声）'},
{'eng': 'I said, "Really. We have to show the other classes how to do it, so when we walk down the hall, people will notice us, so you can\'t make noise. You just have to strut."', 'start': 227, 'time': '03:47', 'chn': '我说，“当然是真的。我们要给 其他班级做个榜样， 当我们走在楼道里， 因为大家都会注意到我们， 我们不能吵闹。 大家要昂首阔步。”'},
{'eng': '(Laughter)', 'start': 237, 'time': '03:57', 'chn': '（笑声）'},
{'eng': 'And I gave them a saying to say: "I am somebody. I was somebody when I came. I\'ll be a better somebody when I leave. I am powerful, and I am strong. I deserve the education that I get here. I have things to do, people to impress, and places to go."', 'start': 238, 'time': '03:58', 'chn': '我还给了他们一个口号： “我是个人物。 我来的时候是个人物。 我毕业的时候会 变成一个更好的人物。 我很有力，很强大。 我值得在这里受教育。 我有很多事情要做， 我要让人们记住我， 我要去很多地方。”'},
{'eng': 'And they said, "Yeah!"', 'start': 253, 'time': '04:13', 'chn': '然后他们说：“是啊！”'},
{'eng': '(Laughter)', 'start': 254, 'time': '04:14', 'chn': '（笑声）'},
{'eng': 'You say it long enough, it starts to be a part of you.', 'start': 256, 'time': '04:16', 'chn': '如果你长时间这么说， 它就会开始变成事实。'},
{'eng': '(Applause)', 'start': 261, 'time': '04:21', 'chn': '（掌声）'},
{'eng': 'I gave a quiz, 20 questions. A student missed 18. I put a "+2" on his paper and a big smiley face.', 'start': 268, 'time': '04:28', 'chn': '我做了一个小测验，20道题。 一个孩子错了18道。 我在他了卷子上写了个 “＋2”和一个大的笑脸。'},
{'eng': '(Laughter)', 'start': 277, 'time': '04:37', 'chn': '（笑声）'},
{'eng': 'He said, "Ms. Pierson, is this an F?"', 'start': 279, 'time': '04:39', 'chn': '他说，“Pierson老师， 这是不及格吗？”'},
{'eng': 'I said, "Yes."', 'start': 283, 'time': '04:43', 'chn': '我说，“是的。”'},
{'eng': '(Laughter)', 'start': 284, 'time': '04:44', 'chn': '（笑声）'},
{'eng': 'He said, "Then why\'d you put a smiley face?"', 'start': 285, 'time': '04:45', 'chn': '他接着说，“那你为什么给我一个笑脸？”'},
{'eng': 'I said, "Because you\'re on a roll. You got two right. You didn\'t miss them all."', 'start': 289, 'time': '04:49', 'chn': '我说，“因为你正渐入佳境。 你没有全错，还对了两个。”'},
{'eng': '(Laughter)', 'start': 294, 'time': '04:54', 'chn': '（笑声）'},
{'eng': 'I said, "And when we review this, won\'t you do better?"', 'start': 295, 'time': '04:55', 'chn': '我说，“我们复习这些题的时候， 难道你不会做得更好吗？”'},
{'eng': 'He said, "Yes, ma\'am, I can do better."', 'start': 298, 'time': '04:58', 'chn': '他说，“是的，老师。我可以做得更好。”'},
{'eng': 'You see, "-18" sucks all the life out of you. "+2" said, "I ain\'t all bad."', 'start': 301, 'time': '05:01', 'chn': '大家看，“－18”让人感觉想死。 “＋2”意味着，“我没有那么糟。”'},
{'eng': "For years, I watched my mother take the time at recess to review, go on home visits in the afternoon, buy combs and brushes and peanut butter and crackers to put in her desk drawer for kids that needed to eat, and a washcloth and some soap for the kids who didn't smell so good. See, it's hard to teach kids who stink.", 'start': 313, 'time': '05:13', 'chn': '好多年了，我看着我妈妈 利用课间休息时间批改作业， 下午去家访， 买梳子、刷子、花生酱和饼干， 把它们放在自己的抽屉里 给那些饿了的孩子们吃， 还有为那些脏孩子们 准备了一条毛巾和一些肥皂。 很明显，教那些发臭的孩子 是一件困难的事。'},
{'eng': '(Laughter)', 'start': 332, 'time': '05:32', 'chn': '（笑声）'},
{'eng': 'And kids can be cruel. And so she kept those things in her desk, and years later, after she retired, I watched some of those same kids come through and say to her, "You know, Ms. Walker, you made a difference in my life. You made it work for me. You made me feel like I was somebody, when I knew, at the bottom, I wasn\'t. And I want you to just see what I\'ve become."', 'start': 334, 'time': '05:34', 'chn': '而孩子们有时也是比较“残忍”的。 所以她把这些东西都放在她的抽屉里， 然后过了很多年，在她退休以后， 我看到一些当年的孩子们回来告诉她， “Walker老师， 您改变了我的生活。 您让它有了意义。 您让我觉得我是个人物， 虽说在心底我知道我不是。 我就是想让您看看我现在 成为了个什么样的人。”'},
{'eng': 'And when my mama died two years ago at 92, there were so many former students at her funeral, it brought tears to my eyes, not because she was gone, but because she left a legacy of relationships that could never disappear.', 'start': 358, 'time': '05:58', 'chn': '当我妈妈两年前 以92岁高龄去世的时候， 有好多好多的以前的学生 来参加了她的葬礼， 我哭了，不是因为她去世了， 而是因为她留下了 这些永远不会消失的 各种联系。'},
{'eng': 'Can we stand to have more relationships? Absolutely. Will you like all your children? Of course not.', 'start': 373, 'time': '06:13', 'chn': '我们真的可以建立更多的关系吗？ 当然可以。 你会喜欢你所有的学生吗？当然不。'},
{'eng': '(Laughter)', 'start': 381, 'time': '06:21', 'chn': '（笑声）'},
{'eng': 'And you know your toughest kids are never absent.', 'start': 383, 'time': '06:23', 'chn': '你也知道那些最难搞的 孩子总是很难甩掉。'},
{'eng': '(Laughter)', 'start': 387, 'time': '06:27', 'chn': '（笑声）'},
{'eng': "Never. You won't like them all, and the tough ones show up for a reason. It's the connection. It's the relationships. So teachers become great actors and great actresses, and we come to work when we don't feel like it, and we're listening to policy that doesn't make sense, and we teach anyway. We teach anyway, because that's what we do.", 'start': 389, 'time': '06:29', 'chn': '永远不会。你不会喜欢每一个人， 然而难搞的那几个的 出现也是有理由的。 这就是联系，是关系。 当你不会喜欢他们每一个人的时候， 关键就是他们永远也不会知道这一点。 所以老师们变成伟大的演员， 我们得强迫自己工作， 我们得听从那些毫无道理的政策， 我们还得上课。 我们还得上课，因为这是我们的责任。'},
{'eng': 'Teaching and learning should bring joy. How powerful would our world be if we had kids who were not afraid to take risks, who were not afraid to think, and who had a champion? Every child deserves a champion, an adult who will never give up on them, who understands the power of connection, and insists that they become the best that they can possibly be.', 'start': 420, 'time': '07:00', 'chn': '教学和学习应该是让人愉快的事情。 我们的世界会变得多么的强大， 如果我们的孩子都不害怕接受挑战， 不害怕思考， 都赢得了一个支持者？ 每个孩子都应该得到别人的支持， 一个成年人要永远不放弃他们， 懂得联系的强大力量， 坚信他们可以变成那个最好的自己。'},
{'eng': "Is this job tough? You betcha. Oh God, you betcha. But it is not impossible. We can do this. We're educators. We're born to make a difference.", 'start': 444, 'time': '07:24', 'chn': '这个职业面临的任务很艰巨吗？ 当然。上帝，毫无疑问。 但是这不是不可能的。 我们可以的，因为我们是教育家。 我们天生就是重塑他人的。'},
{'eng': 'Thank you so much.', 'start': 456, 'time': '07:36', 'chn': '非常感谢大家。'},
{'eng': '(Applause)', 'start': 457, 'time': '07:37', 'chn': '（掌声）'}
];

module.exports.subtitles = subtitles;