var subtitles = [
{'chn': '我在洛杉矶东区长大。 从来没意识到我很穷。 我老爸是街头黑帮头目之一。 大家都知道我是谁， 所以，还真把自己当回事了，我还受到保护， 尽管我老爸 常进班房。 但我有一个非常了不起的母亲，一名非常独立的女性。 她在本地的一间中学工作 是学校主任室的一名秘书。 所以，她要面对很多因为各种原因 被赶出课堂，准备接受处罚的孩子们。 她的办公室总是人满为患的。', 'eng': "So I grew up in East Los Angeles, not even realizing I was poor. My dad was a high-ranking gang member who ran the streets. Everyone knew who I was, so I thought I was a pretty big deal, and I was protected, and even though my dad spent most of my life in and out of jail, I had an amazing mom who was just fiercely independent. She worked at the local high school as a secretary in the dean's office, so she got to see all the kids that got thrown out of class, for whatever reason, who were waiting to be disciplined. Man, her office was packed.", 'time': '00:13', 'start': 13},
{'chn': '象我们这类孩子，要处理许多 校外的问题， 有时我们只是还没准备好集中精神学习而已。 但这并不意味着我们做不到。 只不过我们要比别人多付出一些罢了。 比如说，我记得有一天，我发现我老爸 抽搐、口吐白沫、 因为过量吸毒昏死在浴室的地板上。 说真的，你认为在这样一个晚上 做作业会是我要处理的最重要的事吗？ 当然不是。', 'eng': "So, see, kids like us, we have a lot of things to deal with outside of school, and sometimes we're just not ready to focus. But that doesn't mean that we can't. It just takes a little bit more. Like, I remember one day I found my dad convulsing, foaming at the mouth, OD-ing on the bathroom floor. Really, do you think that doing my homework that night was at the top of my priority list? Not so much.", 'time': '00:48', 'start': 48},
{'chn': '但我确实又很需要一个支持网络， 一群能帮得了我的人 他们可以保证我不会成为 我生活环境的牺牲品， 他们会鞭策我 超越我对自己的期望 我需要老师，在教室里，每一天 他们会对我说：”你能比现在做得更好的“ 但不幸的是，本地的初中 无法满足我的需要 当地帮派林立，老师的更换非常频繁。', 'eng': 'But I really needed a support network, a group of people who were going to help me make sure that I wasn\'t going to be a victim of my own circumstance, that they were going to push me beyond what I even thought I could do. I needed teachers, in the classroom, every day, who were going to say, "You can move beyond that." And unfortunately, the local junior high was not going to offer that. It was gang-infested, huge teacher turnover rate.', 'time': '01:15', 'start': 75},
{'chn': '所以，我妈妈说：“你要每天坐一个半小时的公交车” 到另外一间学校去读书。 所以，在随后的两年里，我就这样去那里读书了。 我每天乘坐校车到镇上富裕繁华的地方 最后我来到这间 学生成分很多样化的学校。 学生当中有些人是帮派成员， 而其他的是我们这些 十分努力完成中学课程的人。 其实，尝试从麻烦当中脱身是在所难免的 因为你要活下来 有时候，就免不了做些身不由己的事。 所以，也有不少老师曾说： “她是读不到毕业的。” 她不接受管教 她不会有任何出路的。 有些老师甚至认定我已经不可救药。', 'eng': 'So my mom said, "You\'re going on a bus an hour and a half away from where we live every day." So for the next two years, that\'s what I did. I took a school bus to the fancy side of town. And eventually, I ended up at a school where there was a mixture. There were some people who were really gang-affiliated, and then there were those of us really trying to make it to high school. Well, trying to stay out of trouble was a little unavoidable. You had to survive. You just had to do things sometimes. So there were a lot of teachers who were like, "She\'s never going to make it. She has an issue with authority. She\'s not going to go anywhere." Some teachers completely wrote me off as a lost cause.', 'time': '01:46', 'start': 106},
{'chn': '所以，当我高中毕业时 他们全都惊呆了。 后来我被Pepperdine大学录取了， 毕业后，我回到我高中时的母校 当了一名特别教育助理。', 'eng': 'But then, they were very surprised when I graduated from high school. I was accepted to Pepperdine University, and I came back to the same school that I attended to be a special ed assistant.', 'time': '02:31', 'start': 151},
{'chn': '后来，我告诉他们：“我要做一名老师。”', 'eng': 'And then I told them, "I want to be a teacher."', 'time': '02:45', 'start': 165},
{'chn': '他们听到后都很惊讶地问我：“什么？”“为什么？” “你怎么会想到要当老师呢？”', 'eng': 'And boy, they were like, "What? Why? Why would you want to do that?"', 'time': '02:50', 'start': 170},
{'chn': '可我就这样开始了我的教学生涯 任教于我的高中母校。 我真的想要挽救更多的 有过和我一样经历的孩子。 所以，每年，我都和我的学生分享我的故事， 因为他们有必要知道每个人都有自己的故事， 每个人都有过挣扎， 而每个人在自己前进的道路上都需要别人拉一把、 护一下。 而我正是那个他们人生旅途上需要找的人。', 'eng': 'So I began my teaching career at the exact same middle school that I attended, and I really wanted to try to save more kids who were just like me. And so every year, I share my background with my kids, because they need to know that everyone has a story, everyone has a struggle, and everyone needs help along the way. And I am going to be their help along the way.', 'time': '02:55', 'start': 175},
{'chn': '所以，作为一个菜鸟老师, 我为他们创造了机会。 一天，一名学生走入我的课堂 他在前一天晚上被人刺伤了。', 'eng': 'So as a rookie teacher, I created opportunity. I had a kid one day come into my class having been stabbed the night before.', 'time': '03:23', 'start': 203},
{'chn': '我对他说：“你得去医院” “或者找学校的护士什么的处理一下你的伤”', 'eng': 'I was like, "You need to go to a hospital, the school nurse, something."', 'time': '03:34', 'start': 214},
{'chn': '可他说：“我不去，老师，我不会去的。” “我得来上课，因为我一定要毕业” 他知道我不会让他 因为自己的生活环境而被拖累， 相反，我们要促使他们迈出第一步和继续向前进。 所以，我很想为这帮孩子营造一个安全的学习环境 想了解他们所经历的一切 想了解他们的家庭 我希望能这样做 但是， 在一间有1600名学生的学校里我没法关注到他们每个人。 而且，年复一年，还有大量的老师离职， 你又怎么能建立师生关系呢？', 'eng': 'He\'s like, "No, Miss, I\'m not going. I need to be in class because I need to graduate." So he knew that I was not going to let him be a victim of his circumstance, but we were going to push forward and keep moving on. And this idea of creating a safe haven for our kids and getting to know exactly what they\'re going through, getting to know their families -- I wanted that, but I couldn\'t do it in a school with 1,600 kids, and teachers turning over year after year after year. How do you get to build those relationships?', 'time': '03:40', 'start': 220},
{'chn': '所以，我们创办了一所新学校。 我们的新校名字是 圣费尔南多应用媒体研究所。 尽管我们仍然要挂靠在我们的学区以获得 资金和支持。 但是，我们享有很大的办学自主权： 如聘请教师的自由 我们只聘那些高效的老师； 同时，我们还拥有课程安排的自由 这样子我们就不会受教材的束缚,不会; 我们还可以控制我们的预算， 将资金花在重要的事情方面， 而不是花在学区或州的教育部门规定的事情上。 我们需要这些自主权。 但此时，我们已经做到了办学模式的彻底转变， 其中的过程是艰辛的，这一革新目前也并非完善。 但我们必须要做好这件事。 我们的社区需要一种新的办法来做好这些孩子的教育工作。', 'eng': "So we created a new school. And we created the San Fernando Institute for Applied Media. And we made sure that we were still attached to our school district for funding, for support. But with that, we were going to gain freedom: freedom to hire the teachers that we knew were going to be effective; freedom to control the curriculum so that we're not doing lesson 1.2 on page five, no; and freedom to control a budget, to spend money where it matters, not how a district or a state says you have to do it. We wanted those freedoms. But now, shifting an entire paradigm, it hasn't been an easy journey, nor is it even complete. But we had to do it. Our community deserved a new way of doing things.", 'time': '04:19', 'start': 259},
{'chn': '作为洛杉矶联合学区内的 第一间试点中学， 自然有人对我们的办学方式提出反对的意见 反对是出于某种担心----- 担心万一办不好怎么办？ 对，如果我们办不好会怎么样呢？ 但问题是，如果我们办好了呢？ 后来，我们的确办得很成功。 所以，尽管老师们反对 因为我们只和老师签定一年期的工作合同---- 如果你教不好，或者你不想教， 你就不能在我们的学校混下去。', 'eng': "And as the very first pilot middle school in all of Los Angeles Unified School District, you better believe there was some opposition. And it was out of fear -- fear of, well, what if they get it wrong? Yeah, what if we get it wrong? But what if we get it right? And we did. So even though teachers were against it because we employ one-year contracts -- you can't teach, or you don't want to teach, you don't get to be at my school with my kids.", 'time': '05:17', 'start': 317},
{'chn': '（掌声）', 'eng': '(Applause)', 'time': '05:51', 'start': 351},
{'chn': '到了我们办学的第三年，我们的学校是什么样子的呢？ 我们已经使学校成为了学生每天都想去的地方了。 我们已经让我们的学生感觉到我们在乎他们。 我们为他们量身定制课程标准， 他们可以使用他们习惯使用的各种电子产品。 手提电脑、台式机，平板电脑----你能想得到的，他们都有。 动画、软件、电影制作软件这些东西他们全都有。 我们把这些东西和他们的学习、生活联系在一起---- 比如说，他们会为癌症协会 做一些公益广告。 这些广告在有轨电车系统上播放。 有说复力的教学当中 没有什么是比这更真更成功的实践了。 我们的州考成绩在不断上升 目前已经比我们学校创办初期提升了80分。', 'eng': "So in our third year, how did we do it? Well, we're making school worth coming to every day. We make our kids feel like they matter to us. We make our curriculum rigorous and relevant to them, and they use all the technology that they're used to. Laptops, computers, tablets -- you name it, they have it. Animation, software, moviemaking software, they have it all. And because we connect it to what they're doing — For example, they made public service announcements for the Cancer Society. These were played in the local trolley system. Teaching elements of persuasion, it doesn't get any more real than that. Our state test scores have gone up more than 80 points since we've become our own school.", 'time': '05:58', 'start': 358},
{'chn': '但这是各利益相关者共同努力的结果--- 如一年工作合同期的老师和校长， 他们的工作时长远远超出了比合同中规定的时间 而没有得到任何额外的补偿。 而且，这还多亏有一名校董 在游说过程中提出一下的表达， “要知道，学区正准备推行这个， 但是你们有另辟蹊径的自由“ 同时，也受益于一个活跃的家长中心 他们并不仅仅是每天露个脸而已 而且积极地参与了学校的治理， 帮他们的孩子-----我们的学生做决策。', 'eng': 'But it\'s taken all stakeholders, working together -- teachers and principals on one-year contracts, working over and above and beyond their contract hours without compensation. And it takes a school board member who is going to lobby for you and say, "Know, the district is trying to impose this, but you have the freedom to do otherwise." And it takes an active parent center who is not only there, showing a presence every day, but who is part of our governance, making decisions for their kids, our kids.', 'time': '06:42', 'start': 402},
{'chn': '为什么我们的学生非得 到离家这么远的地方上学呢？ 他们应该拥有一间在自己的社区里的资质好的学校 一间他们能引以为豪的学校 一间社区为之骄傲的学校， 而他们也需要每天都在为学生争取权利的老师 鼓励他们摆脱目前的困境的老师。 因为，是时候，让像我这样的孩子 不再是非主流，而成为主流了。', 'eng': "Because why should our students have to go so far away from where they live? They deserve a quality school in their neighborhood, a school that they can be proud to say they attend, and a school that the community can be proud of as well, and they need teachers to fight for them every day and empower them to move beyond their circumstances. Because it's time that kids like me stop being the exception, and we become the norm.", 'time': '07:20', 'start': 440},
{'chn': '谢谢。', 'eng': 'Thank you.', 'time': '07:53', 'start': 473},
{'chn': '（掌声）', 'eng': '(Applause)', 'time': '07:54', 'start': 474}
];

module.exports.subtitles = subtitles;