var subtitles = [
{'start': 12, 'end': 15, 'index': '1', 'chn': '当人们发现我写关于时间管理的文章时，', 'eng': 'When people find out I write about time management,'},
{'start': 16, 'end': 18, 'index': '2', 'chn': '他们都会假设两件事：', 'eng': 'they assume two things.'},
{'start': 19, 'end': 22, 'index': '3', 'chn': '第一，我永远都准时，', 'eng': "One is that I'm always on time,"},
{'start': 23, 'end': 24, 'index': '4', 'chn': '但我并不是。', 'eng': "and I'm not."},
{'start': 25, 'end': 26, 'index': '5', 'chn': '我有四个小孩，', 'eng': 'I have four small children,'},
{'start': 26, 'end': 29, 'index': '6', 'chn': '我偶尔将迟到归咎于他们，', 'eng': 'and I would like to blame them for my occasional tardiness,'},
{'start': 29, 'end': 31, 'index': '7', 'chn': '不过有时候真的不是因为他们。', 'eng': "but sometimes it's just not their fault."},
{'start': 32, 'end': 34, 'index': '8', 'chn': '我有一次在去我的一个关于时间管理的演讲时迟到了。', 'eng': 'I was once late to my own speech on time management.'},
{'start': 34, 'end': 35, 'index': '9', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 36, 'end': 39, 'index': '10', 'chn': '我们都需要一点时间去好好地体味一下这有多么讽刺。', 'eng': 'We all had to just take a moment together and savor that irony.'},
{'start': 40, 'end': 44, 'index': '11', 'chn': '第二，人们总是假设我有很多关于', 'eng': 'The second thing they assume is that I have lots of tips and tricks'},
{'start': 44, 'end': 45, 'index': '12', 'chn': '如何节省时间的贴士和技巧。', 'eng': 'for saving bits of time here and there.'},
{'start': 45, 'end': 49, 'index': '13', 'chn': '有时候我听说一些杂志在写这方面的故事，', 'eng': "Sometimes I'll hear from magazines that are doing a story along these lines,"},
{'start': 49, 'end': 53, 'index': '14', 'chn': '通常都是关于教读者如何在一天中获得额外一个小时。', 'eng': 'generally on how to help their readers find an extra hour in the day.'},
{'start': 53, 'end': 56, 'index': '15', 'chn': '基本思路就是从日常的每个活动中挤出一点时间，', 'eng': "And the idea is that we'll shave bits of time off everyday activities,"},
{'start': 56, 'end': 57, 'index': '16', 'chn': '加起来，', 'eng': 'add it up,'},
{'start': 57, 'end': 59, 'index': '17', 'chn': '然后我们就有时间去做更有意思的事情了。', 'eng': "and we'll have time for the good stuff."},
{'start': 59, 'end': 63, 'index': '18', 'chn': '我对这个说法持保留意见，不过我还是愿意听听', 'eng': "I question the entire premise of this piece, but I'm always interested"},
{'start': 63, 'end': 66, 'index': '19', 'chn': '他们在找我之前有什么想法。', 'eng': "in hearing what they've come up with before they call me."},
{'start': 66, 'end': 67, 'index': '20', 'chn': '我最喜欢的几个是：', 'eng': 'Some of my favorites:'},
{'start': 67, 'end': 70, 'index': '21', 'chn': '只完成那些只需要右转的事；', 'eng': 'doing errands where you only have to make right-hand turns --'},
{'start': 70, 'end': 71, 'index': '22', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 71, 'end': 73, 'index': '23', 'chn': '在用微波炉时，要极度审慎：', 'eng': 'Being extremely judicious in microwave usage:'},
{'start': 73, 'end': 76, 'index': '24', 'chn': '当食物包装上面写了3到3.5分钟时，', 'eng': 'it says three to three-and-a-half minutes on the package,'},
{'start': 76, 'end': 79, 'index': '25', 'chn': '我们要挑时间最短的那个。', 'eng': "we're totally getting in on the bottom side of that."},
{'start': 79, 'end': 81, 'index': '26', 'chn': '我个人最喜欢的是，录下你最喜欢看的电视剧，', 'eng': 'And my personal favorite, which makes sense on some level,'},
{'start': 81, 'end': 85, 'index': '27', 'chn': '然后你就可以跳过广告了。其实在某个程度上，还是挺有道理的。', 'eng': 'is to DVR your favorite shows so you can fast-forward through the commercials.'},
{'start': 85, 'end': 87, 'index': '28', 'chn': '这样，你每半个小时就可以挤出八分钟。', 'eng': 'That way, you save eight minutes every half hour,'},
{'start': 87, 'end': 90, 'index': '29', 'chn': '那么你葱用来看电视的两个小时中，', 'eng': 'so in the course of two hours of watching TV,'},
{'start': 90, 'end': 91, 'index': '30', 'chn': '可以挤出32分钟锻炼的时间。', 'eng': 'you find 32 minutes to exercise.'},
{'start': 91, 'end': 92, 'index': '31', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 92, 'end': 93, 'index': '32', 'chn': '倒的确是这么回事儿。', 'eng': 'Which is true.'},
{'start': 94, 'end': 97, 'index': '33', 'chn': '你还知道其他可以找到32分钟锻炼时间的方法吗？', 'eng': 'You know another way to find 32 minutes to exercise?'},
{'start': 97, 'end': 99, 'index': '34', 'chn': '不要每天都看两个小时电视就行了，对吧？', 'eng': "Don't watch two hours of TV a day, right?"},
{'start': 99, 'end': 100, 'index': '35', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 100, 'end': 104, 'index': '36', 'chn': '总之，就是要在各处都省点时间，', 'eng': "Anyway, the idea is we'll save bits of time here and there, add it up,"},
{'start': 104, 'end': 106, 'index': '37', 'chn': '加起来就有时间做我们想做的事了。', 'eng': 'we will finally get to everything we want to do.'},
{'start': 106, 'end': 109, 'index': '38', 'chn': '但在我了解成功的人如何分配时间，', 'eng': 'But after studying how successful people spend their time'},
{'start': 109, 'end': 112, 'index': '39', 'chn': '并看过了他们的时间表后，', 'eng': 'and looking at their schedules hour by hour,'},
{'start': 112, 'end': 115, 'index': '40', 'chn': '我觉得这个想法是完全本末倒置的。', 'eng': 'I think this idea has it completely backward.'},
{'start': 116, 'end': 119, 'index': '41', 'chn': '我们不是通过节省时间来打造我们想过的生活。', 'eng': "We don't build the lives we want by saving time."},
{'start': 120, 'end': 121, 'index': '42', 'chn': '我们应该先建立我们想要的生活，', 'eng': 'We build the lives we want,'},
{'start': 122, 'end': 125, 'index': '43', 'chn': '时间就会自然而然节省出来。', 'eng': 'and then time saves itself.'},
{'start': 127, 'end': 128, 'index': '44', 'chn': '我来解释一下。', 'eng': "Here's what I mean."},
{'start': 128, 'end': 129, 'index': '45', 'chn': '我最近有个时间日记项目，', 'eng': 'I recently did a time diary project'},
{'start': 129, 'end': 134, 'index': '46', 'chn': '观察最忙碌的女士生命中的1001天。', 'eng': 'looking at 1,001 days in the lives of extremely busy women.'},
{'start': 134, 'end': 136, 'index': '47', 'chn': '她们工作繁忙，有时候是自己的生意，', 'eng': 'They had demanding jobs, sometimes their own businesses,'},
{'start': 136, 'end': 138, 'index': '48', 'chn': '有时候要照顾自己的孩子，或者是照顾父母，', 'eng': 'kids to care for, maybe parents to care for,'},
{'start': 138, 'end': 140, 'index': '49', 'chn': '还有服务社区等等——', 'eng': 'community commitments --'},
{'start': 140, 'end': 142, 'index': '50', 'chn': '都是一些很忙的人。', 'eng': 'busy, busy people.'},
{'start': 142, 'end': 144, 'index': '51', 'chn': '我让她们记录了一星期的行程，', 'eng': 'I had them keep track of their time for a week'},
{'start': 144, 'end': 147, 'index': '52', 'chn': '计算她们工作和睡觉的时间，', 'eng': 'so I could add up how much they worked and slept,'},
{'start': 147, 'end': 149, 'index': '53', 'chn': '为了我的书，我还采访了解了她们的常用策略。', 'eng': 'and I interviewed them about their strategies, for my book.'},
{'start': 150, 'end': 152, 'index': '54', 'chn': '其中一个被我研究过时间表的女士，', 'eng': 'One of the women whose time log I studied'},
{'start': 152, 'end': 154, 'index': '55', 'chn': '在一个周三晚上出去了一趟，', 'eng': 'goes out on a Wednesday night for something.'},
{'start': 154, 'end': 156, 'index': '56', 'chn': '回家发现她的热水器坏了，', 'eng': 'She comes home to find that her water heater has broken,'},
{'start': 156, 'end': 159, 'index': '57', 'chn': '地下室都被水淹了。', 'eng': 'and there is now water all over her basement.'},
{'start': 160, 'end': 162, 'index': '58', 'chn': '如果你也遇到过这种事儿的话，', 'eng': "If you've ever had anything like this happen to you,"},
{'start': 162, 'end': 165, 'index': '59', 'chn': '你会知道眼前的景象多么令人崩溃和沮丧。', 'eng': 'you know it is a hugely damaging, frightening, sopping mess.'},
{'start': 165, 'end': 168, 'index': '60', 'chn': '于是那个晚上她立刻着手处理，', 'eng': "So she's dealing with the immediate aftermath that night,"},
{'start': 168, 'end': 170, 'index': '61', 'chn': '第二天她找了一个水管工，', 'eng': "next day she's got plumbers coming in,"},
{'start': 170, 'end': 173, 'index': '62', 'chn': '第三天找了专业的清理人员来处理损坏的地毯。', 'eng': 'day after that, professional cleaning crew dealing with the ruined carpet.'},
{'start': 173, 'end': 175, 'index': '63', 'chn': '所有这些都算在了她的时间表内。', 'eng': 'All this is being recorded on her time log.'},
{'start': 175, 'end': 178, 'index': '64', 'chn': '总共花了她一周中的七个小时。', 'eng': 'Winds up taking seven hours of her week.'},
{'start': 179, 'end': 180, 'index': '65', 'chn': '七个小时。', 'eng': 'Seven hours.'},
{'start': 180, 'end': 183, 'index': '66', 'chn': '这就等于一周七天每天都要挤出一个小时。', 'eng': "That's like finding an extra hour in the day."},
{'start': 184, 'end': 187, 'index': '67', 'chn': '但是假如你在这一周刚开始时就问她，', 'eng': "But I'm sure if you had asked her at the start of the week,"},
{'start': 187, 'end': 190, 'index': '68', 'chn': '“你能在这周抽出七个小时来参加铁人三项吗？”，', 'eng': '"Could you find seven hours to train for a triathlon?"'},
{'start': 191, 'end': 195, 'index': '69', 'chn': '“你能在这周抽出七个小时指导七个有潜力的人吗？“', 'eng': '"Could you find seven hours to mentor seven worthy people?"'},
{'start': 195, 'end': 198, 'index': '70', 'chn': '我确定她会像大多数人一样，', 'eng': "I'm sure she would've said what most of us would've said,"},
{'start': 198, 'end': 202, 'index': '71', 'chn': '说，”怎么可能，你看不出我有多忙吗？“', 'eng': 'which is, "No -- can\'t you see how busy I am?"'},
{'start': 203, 'end': 205, 'index': '72', 'chn': '但是她最后不得不抽出七个小时，', 'eng': 'Yet when she had to find seven hours'},
{'start': 205, 'end': 207, 'index': '73', 'chn': '因为她的地下室都被水淹了，', 'eng': 'because there is water all over her basement,'},
{'start': 207, 'end': 210, 'index': '74', 'chn': '她挤出了这七个小时。', 'eng': 'she found seven hours.'},
{'start': 210, 'end': 215, 'index': '75', 'chn': '这件事告诉我们：时间是有弹性的。', 'eng': 'And what this shows us is that time is highly elastic.'},
{'start': 215, 'end': 217, 'index': '76', 'chn': '我们不能创造更多时间，', 'eng': 'We cannot make more time,'},
{'start': 217, 'end': 221, 'index': '77', 'chn': '但是时间会自己调整去适应我们选择去做的事情。', 'eng': 'but time will stretch to accommodate what we choose to put into it.'},
{'start': 222, 'end': 224, 'index': '78', 'chn': '所以时间管理的关键就是', 'eng': 'And so the key to time management'},
{'start': 225, 'end': 227, 'index': '79', 'chn': '对待最重要的事情应该像', 'eng': 'is treating our priorities'},
{'start': 227, 'end': 230, 'index': '80', 'chn': '对待那个坏了的热水器一样。', 'eng': 'as the equivalent of that broken water heater.'},
{'start': 231, 'end': 233, 'index': '81', 'chn': '要做到这一点，', 'eng': 'To get at this,'},
{'start': 233, 'end': 236, 'index': '82', 'chn': '我要借用我采访过最忙的人的话。', 'eng': 'I like to use language from one of the busiest people I ever interviewed.'},
{'start': 236, 'end': 238, 'index': '83', 'chn': '她经营着一个小企业，', 'eng': 'By busy, I mean she was running a small business'},
{'start': 238, 'end': 240, 'index': '84', 'chn': '请了十二名员工，', 'eng': 'with 12 people on the payroll,'},
{'start': 240, 'end': 242, 'index': '85', 'chn': '空余时间她还要照顾六个孩子。', 'eng': 'she had six children in her spare time.'},
{'start': 242, 'end': 245, 'index': '86', 'chn': '我联系上了她，想要采访她关于', 'eng': 'I was getting in touch with her to set up an interview'},
{'start': 245, 'end': 247, 'index': '87', 'chn': '她是怎么做到“无所不能”的。', 'eng': 'on how she "had it all" -- that phrase.'},
{'start': 247, 'end': 249, 'index': '88', 'chn': '我记得那是一个星期四的早晨，', 'eng': 'I remember it was a Thursday morning,'},
{'start': 249, 'end': 251, 'index': '89', 'chn': '她没时间和我说话。', 'eng': 'and she was not available to speak with me.'},
{'start': 251, 'end': 252, 'index': '90', 'chn': '当然了，她很忙。', 'eng': 'Of course, right?'},
{'start': 252, 'end': 255, 'index': '91', 'chn': '但是她没时间和我说话的原因是，', 'eng': 'But the reason she was unavailable to speak with me'},
{'start': 255, 'end': 257, 'index': '92', 'chn': '她去远足了。', 'eng': 'is that she was out for a hike,'},
{'start': 257, 'end': 259, 'index': '93', 'chn': '因为那是春季一个美丽的清晨，', 'eng': 'because it was a beautiful spring morning,'},
{'start': 259, 'end': 260, 'index': '94', 'chn': '所以她去远足了。', 'eng': 'and she wanted to go for a hike.'},
{'start': 260, 'end': 263, 'index': '95', 'chn': '这样的她让我变得更感兴趣了，', 'eng': 'So of course this makes me even more intrigued,'},
{'start': 263, 'end': 266, 'index': '96', 'chn': '当我最终联系上她时，', 'eng': 'and when I finally do catch up with her, she explains it like this.'},
{'start': 266, 'end': 268, 'index': '97', 'chn': '她说：“听我说，劳拉，我做的所有的事情，', 'eng': 'She says, "Listen Laura, everything I do,'},
{'start': 269, 'end': 273, 'index': '98', 'chn': '我花的每分每秒，都是我的选择。”', 'eng': 'every minute I spend, is my choice."'},
{'start': 273, 'end': 274, 'index': '99', 'chn': '所以与其说，', 'eng': 'And rather than say,'},
{'start': 274, 'end': 277, 'index': '100', 'chn': '”我没有时间做这个，这个，或者那个。”', 'eng': '"I don\'t have time to do x, y or z,"'},
{'start': 277, 'end': 282, 'index': '101', 'chn': '她会说：”我不做这些事情因为这些不是我的首要任务。“', 'eng': 'she\'d say, "I don\'t do x, y or z because it\'s not a priority."'},
{'start': 283, 'end': 287, 'index': '102', 'chn': '“我没有时间”的意思通常是”那不是我的首要任务”。', 'eng': '"I don\'t have time," often means "It\'s not a priority."'},
{'start': 288, 'end': 291, 'index': '103', 'chn': '其实你想想，那的确是更准确的说法。', 'eng': "If you think about it, that's really more accurate language."},
{'start': 291, 'end': 294, 'index': '104', 'chn': '我可能会告诉你我没有时间清理百叶窗，', 'eng': "I could tell you I don't have time to dust my blinds,"},
{'start': 294, 'end': 295, 'index': '105', 'chn': '但那不是真的。', 'eng': "but that's not true."},
{'start': 295, 'end': 298, 'index': '106', 'chn': '假如你愿意付我10万美金让我给百叶窗除尘，', 'eng': 'If you offered to pay me $100,000 to dust my blinds,'},
{'start': 298, 'end': 299, 'index': '107', 'chn': '我会马上就去做。', 'eng': 'I would get to it pretty quickly.'},
{'start': 299, 'end': 300, 'index': '108', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 300, 'end': 302, 'index': '109', 'chn': '既然那不可能发生，', 'eng': 'Since that is not going to happen,'},
{'start': 302, 'end': 304, 'index': '110', 'chn': '我可以说不是因为时间不够，', 'eng': 'I can acknowledge this is not a matter of lacking time;'},
{'start': 305, 'end': 306, 'index': '111', 'chn': '而是我不想做。', 'eng': "it's that I don't want to do it."},
{'start': 306, 'end': 310, 'index': '112', 'chn': '这么说提醒了我们，时间是一种选择。', 'eng': 'Using this language reminds us that time is a choice.'},
{'start': 310, 'end': 311, 'index': '113', 'chn': '我会告诉你，', 'eng': 'And granted,'},
{'start': 311, 'end': 314, 'index': '114', 'chn': '当然，不同的选择有时候会', 'eng': 'there may be horrible consequences for making different choices,'},
{'start': 314, 'end': 315, 'index': '115', 'chn': '带来可怕的后果。', 'eng': 'I will give you that.'},
{'start': 315, 'end': 317, 'index': '116', 'chn': '但是我们都是聪明人，', 'eng': 'But we are smart people,'},
{'start': 317, 'end': 319, 'index': '117', 'chn': '从长远来看，', 'eng': 'and certainly over the long run,'},
{'start': 319, 'end': 321, 'index': '118', 'chn': '我们有能力去选择一些值得做的事，', 'eng': 'we have the power to fill our lives'},
{'start': 321, 'end': 323, 'index': '119', 'chn': '来填补我们生命中的时间。', 'eng': 'with the things that deserve to be there.'},
{'start': 325, 'end': 326, 'index': '120', 'chn': '那么我们应该怎么做呢？', 'eng': 'So how do we do that?'},
{'start': 326, 'end': 328, 'index': '121', 'chn': '我们要如何像对待那个', 'eng': 'How do we treat our priorities'},
{'start': 328, 'end': 330, 'index': '122', 'chn': '坏了的热水器一样对待我们的首要任务？', 'eng': 'as the equivalent of that broken water heater?'},
{'start': 331, 'end': 333, 'index': '123', 'chn': '首先，我们需要找出哪些事最重要。', 'eng': 'Well, first we need to figure out what they are.'},
{'start': 333, 'end': 336, 'index': '124', 'chn': '我想给你们分享两个技巧。', 'eng': 'I want to give you two strategies for thinking about this.'},
{'start': 336, 'end': 338, 'index': '125', 'chn': '第一个，从职业的角度来说：', 'eng': 'The first, on the professional side:'},
{'start': 338, 'end': 340, 'index': '126', 'chn': '我相信许多人在年底的时候', 'eng': "I'm sure many people coming up to the end of the year"},
{'start': 340, 'end': 343, 'index': '127', 'chn': '会发出或者收到年度绩效审查。', 'eng': 'are giving or getting annual performance reviews.'},
{'start': 343, 'end': 345, 'index': '128', 'chn': '你回头看看这一年的成功和', 'eng': 'You look back over your successes over the year,'},
{'start': 345, 'end': 347, 'index': '129', 'chn': '“成长的机会”。', 'eng': 'your "opportunities for growth."'},
{'start': 347, 'end': 349, 'index': '130', 'chn': '这的确起到了它的作用，', 'eng': 'And this serves its purpose,'},
{'start': 350, 'end': 352, 'index': '131', 'chn': '但是我发现往前看会更有效。', 'eng': "but I find it's more effective to do this looking forward."},
{'start': 352, 'end': 355, 'index': '132', 'chn': '我想让你们把这当做下一年的年底。', 'eng': "So I want you to pretend it's the end of next year."},
{'start': 356, 'end': 358, 'index': '133', 'chn': '你在给自己做年度绩效审查，', 'eng': "You're giving yourself a performance review,"},
{'start': 358, 'end': 363, 'index': '134', 'chn': '在专业方面，这一年的表现非常出众。', 'eng': 'and it has been an absolutely amazing year for you professionally.'},
{'start': 363, 'end': 369, 'index': '135', 'chn': '是哪三到五件事使这一年变得如此出众？', 'eng': 'What three to five things did you do that made it so amazing?'},
{'start': 370, 'end': 374, 'index': '136', 'chn': '你现在就可以写明年的绩效审查。', 'eng': "So you can write next year's performance review now."},
{'start': 374, 'end': 376, 'index': '137', 'chn': '你也可以在个人生活方面这么做。', 'eng': 'And you can do this for your personal life, too.'},
{'start': 376, 'end': 379, 'index': '138', 'chn': '我相信你们许多人，包括我，在十二月，', 'eng': "I'm sure many of you, like me, come December,"},
{'start': 379, 'end': 382, 'index': '139', 'chn': '都会收到这种夹着彩色纸的卡片。', 'eng': 'get cards that contain these folded up sheets of colored paper,'},
{'start': 383, 'end': 388, 'index': '140', 'chn': '上面写着“家庭假日信件”。', 'eng': 'on which is written what is known as the family holiday letter.'},
{'start': 388, 'end': 389, 'index': '141', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 389, 'end': 392, 'index': '142', 'chn': '听起来像是一个挺悲惨的文学题材，', 'eng': 'Bit of a wretched genre of literature, really,'},
{'start': 392, 'end': 395, 'index': '143', 'chn': '谈论家里每个人有多了不起，', 'eng': 'going on about how amazing everyone in the household is,'},
{'start': 395, 'end': 397, 'index': '144', 'chn': '或者更精彩点，', 'eng': 'or even more scintillating,'},
{'start': 397, 'end': 399, 'index': '145', 'chn': '家里每个人有多忙。', 'eng': 'how busy everyone in the household is.'},
{'start': 399, 'end': 401, 'index': '146', 'chn': '但是这些信有它们的用处，', 'eng': 'But these letters serve a purpose,'},
{'start': 401, 'end': 403, 'index': '147', 'chn': '它们告诉你的朋友和家人', 'eng': 'which is that they tell your friends and family'},
{'start': 403, 'end': 406, 'index': '148', 'chn': '你这一年里做了什么对个人生活有意义的事。', 'eng': 'what you did in your personal life that mattered to you over the year.'},
{'start': 406, 'end': 408, 'index': '149', 'chn': '那么今年快要结束了，', 'eng': "So this year's kind of done,"},
{'start': 408, 'end': 410, 'index': '150', 'chn': '我想让你假装这是明年的年底，', 'eng': "but I want you to pretend it's the end of next year,"},
{'start': 410, 'end': 413, 'index': '151', 'chn': '对你和你在乎的人来说，', 'eng': 'and it has been an absolutely amazing year'},
{'start': 413, 'end': 416, 'index': '152', 'chn': '这都是无与伦比的一年。', 'eng': 'for you and the people you care about.'},
{'start': 417, 'end': 421, 'index': '153', 'chn': '哪三到五件事让你这一年表现如此出色？', 'eng': 'What three to five things did you do that made it so amazing?'},
{'start': 422, 'end': 426, 'index': '154', 'chn': '其实你现在就可以写明年的家庭假日信件了。', 'eng': "So you can write next year's family holiday letter now."},
{'start': 427, 'end': 428, 'index': '155', 'chn': '先不要发出去。', 'eng': "Don't send it."},
{'start': 428, 'end': 429, 'index': '156', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 429, 'end': 432, 'index': '157', 'chn': '真的，不要发出去。', 'eng': "Please, don't send it."},
{'start': 432, 'end': 434, 'index': '158', 'chn': '但是你可以写。', 'eng': 'But you can write it.'},
{'start': 434, 'end': 437, 'index': '159', 'chn': '现在，有了绩效评估和写给家人的信，', 'eng': 'And now, between the performance review and the family holiday letter,'},
{'start': 438, 'end': 441, 'index': '160', 'chn': '我们就有了六到十个明年可以努力的目标。', 'eng': 'we have a list of six to ten goals we can work on in the next year.'},
{'start': 441, 'end': 444, 'index': '161', 'chn': '我们需要先把他们分成可行的阶段性任务。', 'eng': 'And now we need to break these down into doable steps.'},
{'start': 444, 'end': 446, 'index': '162', 'chn': '或许你要写一个家族传记。', 'eng': 'So maybe you want to write a family history.'},
{'start': 446, 'end': 448, 'index': '163', 'chn': '首先，你可以读读别人的家族历史，', 'eng': 'First, you can read some other family histories,'},
{'start': 448, 'end': 449, 'index': '164', 'chn': '了解一下大概的风格。', 'eng': 'get a sense for the style.'},
{'start': 449, 'end': 453, 'index': '165', 'chn': '然后可以想象你要问亲戚的问题，', 'eng': 'Then maybe think about the questions you want to ask your relatives,'},
{'start': 453, 'end': 454, 'index': '166', 'chn': '约定和他们见面谈话的时间。', 'eng': 'set up appointments to interview them.'},
{'start': 455, 'end': 456, 'index': '167', 'chn': '或者你想要参加一个五千米的短程马拉松。', 'eng': 'Or maybe you want to run a 5K.'},
{'start': 456, 'end': 459, 'index': '168', 'chn': '你需要先找一个竞赛报名，再做一个培训计划，', 'eng': 'So you need to find a race and sign up, figure out a training plan,'},
{'start': 459, 'end': 462, 'index': '169', 'chn': '从衣柜底下翻出你的运动鞋。', 'eng': 'and dig those shoes out of the back of the closet.'},
{'start': 462, 'end': 464, 'index': '170', 'chn': '然后——这是关键——', 'eng': 'And then -- this is key --'},
{'start': 464, 'end': 468, 'index': '171', 'chn': '我们将我们的首要事件视为那个坏掉的热水器，', 'eng': 'we treat our priorities as the equivalent of that broken water heater,'},
{'start': 468, 'end': 471, 'index': '172', 'chn': '将它们优先放入我们的日程表里。', 'eng': 'by putting them into our schedules first.'},
{'start': 471, 'end': 476, 'index': '173', 'chn': '我们要在事情发生的几周前就先想好。', 'eng': 'We do this by thinking through our weeks before we are in them.'},
{'start': 476, 'end': 480, 'index': '174', 'chn': '我发现周五的下午最适合处理这事儿。', 'eng': 'I find a really good time to do this is Friday afternoons.'},
{'start': 480, 'end': 483, 'index': '175', 'chn': '周五的下午是被经济学家称为', 'eng': 'Friday afternoon is what an economist might call'},
{'start': 483, 'end': 485, 'index': '176', 'chn': '“低机会成本”时间。', 'eng': 'a "low opportunity cost" time.'},
{'start': 486, 'end': 489, 'index': '177', 'chn': '我们大部分人不会在周五下午想着，', 'eng': 'Most of us are not sitting there on Friday afternoons saying,'},
{'start': 489, 'end': 491, 'index': '178', 'chn': '“我要朝我的个人和', 'eng': '"I am excited to make progress'},
{'start': 491, 'end': 493, 'index': '179', 'chn': '职业生涯的首要事件迈进了，', 'eng': 'toward my personal and professional priorities'},
{'start': 493, 'end': 494, 'index': '180', 'chn': '所以很兴奋。“', 'eng': 'right now."'},
{'start': 494, 'end': 495, 'index': '181', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 495, 'end': 498, 'index': '182', 'chn': '但是我们愿意去想那些事是什么。', 'eng': 'But we are willing to think about what those should be.'},
{'start': 498, 'end': 500, 'index': '183', 'chn': '所以在周五下午花一点时间，', 'eng': 'So take a little bit of time Friday afternoon,'},
{'start': 500, 'end': 507, 'index': '184', 'chn': '为自己做一个分成三类的首要事件的列表：事业，人际关系，个人。', 'eng': 'make yourself a three-category priority list: career, relationships, self.'},
{'start': 508, 'end': 511, 'index': '185', 'chn': '这样的三项分类列表提醒了我们', 'eng': 'Making a three-category list reminds us'},
{'start': 511, 'end': 514, 'index': '186', 'chn': '每一个类别都应该有一些事。', 'eng': 'that there should be something in all three categories.'},
{'start': 514, 'end': 516, 'index': '187', 'chn': '事业，我们经常考虑；', 'eng': 'Career, we think about;'},
{'start': 516, 'end': 517, 'index': '188', 'chn': '人际关系，个人——', 'eng': 'relationships, self --'},
{'start': 517, 'end': 519, 'index': '189', 'chn': '很少会想。', 'eng': 'not so much.'},
{'start': 519, 'end': 520, 'index': '190', 'chn': '无论如何，只要一个短短的列表，', 'eng': 'But anyway, just a short list,'},
{'start': 521, 'end': 522, 'index': '191', 'chn': '每个都包含两到三件事。', 'eng': 'two to three items in each.'},
{'start': 522, 'end': 525, 'index': '192', 'chn': '它们会帮助我们看清下周，', 'eng': 'Then look out over the whole of the next week,'},
{'start': 525, 'end': 526, 'index': '193', 'chn': '如何在下周计划这些事情。', 'eng': 'and see where you can plan them in.'},
{'start': 527, 'end': 530, 'index': '194', 'chn': '你可以决定如何计划。', 'eng': 'Where you plan them in is up to you.'},
{'start': 530, 'end': 533, 'index': '195', 'chn': '这可能对一些人来说会比较困难一点。', 'eng': 'I know this is going to be more complicated for some people than others.'},
{'start': 533, 'end': 537, 'index': '196', 'chn': '我的意思是，有些人的人生就是比较复杂。', 'eng': "I mean, some people's lives are just harder than others."},
{'start': 537, 'end': 540, 'index': '197', 'chn': '如果你自己有好几个要照顾的小孩，', 'eng': 'It is not going to be easy to find time to take that poetry class'},
{'start': 540, 'end': 543, 'index': '198', 'chn': '想要找时间去参加诗歌班一定不容易。', 'eng': 'if you are caring for multiple children on your own.'},
{'start': 543, 'end': 545, 'index': '199', 'chn': '我懂。', 'eng': 'I get that.'},
{'start': 545, 'end': 547, 'index': '200', 'chn': '我不想轻视任何人的困难。', 'eng': "And I don't want to minimize anyone's struggle."},
{'start': 547, 'end': 551, 'index': '201', 'chn': '当是我觉得我接下来要说的数字是会改变你的想法的。', 'eng': 'But I do think that the numbers I am about to tell you are empowering.'},
{'start': 552, 'end': 556, 'index': '202', 'chn': '我们每周都有168个小时。', 'eng': 'There are 168 hours in a week.'},
{'start': 557, 'end': 562, 'index': '203', 'chn': '24乘以7是168个小时。', 'eng': 'Twenty-four times seven is 168 hours.'},
{'start': 563, 'end': 565, 'index': '204', 'chn': '这是一段很长时间。', 'eng': 'That is a lot of time.'},
{'start': 566, 'end': 569, 'index': '205', 'chn': '假如你有一个全职的工作，一周是40个小时，', 'eng': 'If you are working a full-time job, so 40 hours a week,'},
{'start': 569, 'end': 572, 'index': '206', 'chn': '每晚睡八个小时，一周是56个小时，', 'eng': 'sleeping eight hours a night, so 56 hours a week --'},
{'start': 572, 'end': 575, 'index': '207', 'chn': '我们有剩下72个小时来做其他事情。', 'eng': 'that leaves 72 hours for other things.'},
{'start': 576, 'end': 578, 'index': '208', 'chn': '这是一段很长的时间。', 'eng': 'That is a lot of time.'},
{'start': 578, 'end': 580, 'index': '209', 'chn': '假如你说你每周工作50个小时，', 'eng': "You say you're working 50 hours a week,"},
{'start': 580, 'end': 582, 'index': '210', 'chn': '比如一份全职和一份兼职。', 'eng': 'maybe a main job and a side hustle.'},
{'start': 582, 'end': 585, 'index': '211', 'chn': '这样你还是有60小时去做其他的事情。', 'eng': 'Well, that leaves 62 hours for other things.'},
{'start': 585, 'end': 587, 'index': '212', 'chn': '假如你说你每周工作60个小时，', 'eng': "You say you're working 60 hours."},
{'start': 587, 'end': 589, 'index': '213', 'chn': '你还是有52个小时去做其他的事情。', 'eng': 'Well, that leaves 52 hours for other things.'},
{'start': 589, 'end': 591, 'index': '214', 'chn': '你说你每周工作超过60个小时，', 'eng': "You say you're working more than 60 hours."},
{'start': 591, 'end': 593, 'index': '215', 'chn': '你确定吗？', 'eng': 'Well, are you sure?'},
{'start': 593, 'end': 594, 'index': '216', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 594, 'end': 597, 'index': '217', 'chn': '曾经有一个研究对比了人们估计的工作时间，', 'eng': "There was once a study comparing people's estimated work weeks"},
{'start': 597, 'end': 599, 'index': '218', 'chn': '和实际的工作日记。', 'eng': 'with time diaries.'},
{'start': 599, 'end': 601, 'index': '219', 'chn': '他们发现那些表示工作超过75小时的人，', 'eng': 'They found that people claiming 75-plus-hour work weeks'},
{'start': 601, 'end': 604, 'index': '220', 'chn': '有25小时的误差。', 'eng': 'were off by about 25 hours.'},
{'start': 604, 'end': 605, 'index': '221', 'chn': '（笑声）', 'eng': '(Laughter)'},
{'start': 605, 'end': 608, 'index': '222', 'chn': '你可以猜到这个误差是多了还是少了吧？', 'eng': 'You can guess in which direction, right?'},
{'start': 609, 'end': 611, 'index': '223', 'chn': '无论如何，在一周的168个小时里，', 'eng': 'Anyway, in 168 hours a week,'},
{'start': 611, 'end': 614, 'index': '224', 'chn': '我觉得我们总可以找到时间做我们想做的事。', 'eng': 'I think we can find time for what matters to you.'},
{'start': 614, 'end': 616, 'index': '225', 'chn': '如果你想花时间陪陪你的孩子，', 'eng': 'If you want to spend more time with your kids,'},
{'start': 616, 'end': 619, 'index': '226', 'chn': '或者准备你即将到来的考试，', 'eng': "you want to study more for a test you're taking,"},
{'start': 619, 'end': 622, 'index': '227', 'chn': '你想锻炼两三个小时或者做两个小时志愿者，', 'eng': 'you want to exercise for three hours and volunteer for two,'},
{'start': 622, 'end': 623, 'index': '228', 'chn': '你都可以的。', 'eng': 'you can.'},
{'start': 623, 'end': 627, 'index': '229', 'chn': '即便你的工作时间远超过法定时间。', 'eng': "And that's even if you're working way more than full-time hours."},
{'start': 627, 'end': 629, 'index': '230', 'chn': '所以我们有很多时间，这很好。', 'eng': 'So we have plenty of time, which is great,'},
{'start': 629, 'end': 631, 'index': '231', 'chn': '但是你知道吗？', 'eng': 'because guess what?'},
{'start': 631, 'end': 633, 'index': '232', 'chn': '我们根本不需要那么多时间去完成一个大目标。', 'eng': "We don't even need that much time to do amazing things."},
{'start': 634, 'end': 637, 'index': '233', 'chn': '但当我们有一点空闲时间的时候，我们会做什么？', 'eng': 'But when most of us have bits of time, what do we do?'},
{'start': 637, 'end': 639, 'index': '234', 'chn': '拿出手机，是吧？', 'eng': 'Pull out the phone, right?'},
{'start': 639, 'end': 641, 'index': '235', 'chn': '开始删除邮件。', 'eng': 'Start deleting emails.'},
{'start': 642, 'end': 644, 'index': '236', 'chn': '或者在家里闲逛，', 'eng': "Otherwise, we're puttering around the house"},
{'start': 644, 'end': 645, 'index': '237', 'chn': '看电视。', 'eng': 'or watching TV.'},
{'start': 645, 'end': 648, 'index': '238', 'chn': '但是每个不起眼的时刻都潜力无限。', 'eng': 'But small moments can have great power.'},
{'start': 649, 'end': 651, 'index': '239', 'chn': '你可以用零星的时间，', 'eng': 'You can use your bits of time'},
{'start': 651, 'end': 654, 'index': '240', 'chn': '来获得零星的快乐。', 'eng': 'for bits of joy.'},
{'start': 655, 'end': 657, 'index': '241', 'chn': '比如说在去上班的公车上', 'eng': "Maybe it's choosing to read something wonderful on the bus"},
{'start': 657, 'end': 659, 'index': '242', 'chn': '读一些精彩的东西。', 'eng': 'on the way to work.'},
{'start': 659, 'end': 661, 'index': '243', 'chn': '当我以前的工作需要我每天早上乘两趟公车', 'eng': 'I know when I had a job that required two bus rides'},
{'start': 661, 'end': 663, 'index': '244', 'chn': '和一趟地铁的时候，', 'eng': 'and a subway ride every morning,'},
{'start': 663, 'end': 666, 'index': '245', 'chn': '我周末会去图书馆找东西来读。', 'eng': 'I used to go to the library on weekends to get stuff to read.'},
{'start': 666, 'end': 670, 'index': '246', 'chn': '这几乎，几乎让我的生活更丰富了。', 'eng': 'It made the whole experience almost, almost, enjoyable.'},
{'start': 671, 'end': 674, 'index': '247', 'chn': '工作间隙的休息时间可以用来冥想或者祷告。', 'eng': 'Breaks at work can be used for meditating or praying.'},
{'start': 675, 'end': 678, 'index': '248', 'chn': '如果你因为工作忙而不能吃家庭晚餐，', 'eng': 'If family dinner is out because of your crazy work schedule,'},
{'start': 678, 'end': 681, 'index': '249', 'chn': '试一下家庭早餐。', 'eng': 'maybe family breakfast could be a good substitute.'},
{'start': 681, 'end': 684, 'index': '250', 'chn': '这就是看着一个人所有的时间，', 'eng': "It's about looking at the whole of one's time"},
{'start': 684, 'end': 686, 'index': '251', 'chn': '然后找到什么时候可以做想做的事。', 'eng': 'and seeing where the good stuff can go.'},
{'start': 688, 'end': 690, 'index': '252', 'chn': '我真的相信，', 'eng': 'I truly believe this.'},
{'start': 690, 'end': 693, 'index': '253', 'chn': '我们都有充分的时间。', 'eng': 'There is time.'},
{'start': 694, 'end': 696, 'index': '254', 'chn': '就算我们很忙，', 'eng': 'Even if we are busy,'},
{'start': 697, 'end': 698, 'index': '255', 'chn': '我们仍然有时间去做重要的事。', 'eng': 'we have time for what matters.'},
{'start': 699, 'end': 701, 'index': '256', 'chn': '当我们关注在重要的事上时，', 'eng': 'And when we focus on what matters,'},
{'start': 702, 'end': 703, 'index': '257', 'chn': '我们可以用所拥有的时间', 'eng': 'we can build the lives we want'},
{'start': 704, 'end': 705, 'index': '258', 'chn': '创造我们想要的生活。', 'eng': "in the time we've got."},
{'start': 706, 'end': 707, 'index': '259', 'chn': '谢谢。', 'eng': 'Thank you.'},
{'start': 707, 'end': 712, 'index': '260', 'chn': '（鼓掌）', 'eng': '(Applause)'}
];

module.exports.subtitles = subtitles;